# Generated by Django 3.2.4 on 2021-06-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=25)),
                ('city_longitude', models.IntegerField(default=0)),
                ('city_latitude', models.IntegerField(default=0)),
                ('zip_code', models.IntegerField(default=0)),
                ('country_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UsersCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField(default=0)),
                ('added_on', models.DateTimeField(verbose_name='Added on')),
                ('users_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Calendar Date')),
                ('min_temp', models.IntegerField(default=0)),
                ('max_temp', models.IntegerField(default=0)),
                ('avg_humidity', models.IntegerField(default=0)),
                ('sunrise_time', models.TimeField(verbose_name='Sunrise:')),
                ('sunset_time', models.TimeField(verbose_name='Sunset:')),
                ('last_updated', models.DateTimeField(verbose_name='Last updated')),
                ('city_id', models.IntegerField(default=0)),
                ('weather_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherHourly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('feels_like_temp', models.IntegerField(default=0)),
                ('humidity', models.IntegerField(default=0)),
                ('wind_speed', models.IntegerField(default=0)),
                ('wind_direction', models.IntegerField(default=0)),
                ('pressure', models.IntegerField(default=0)),
                ('visibility', models.IntegerField(default=0)),
                ('city_id', models.IntegerField(default=0)),
                ('weather_status', models.IntegerField(default=0)),
            ],
        ),
    ]
