# Generated by Django 3.2.4 on 2021-06-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weatherhourly_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdaily',
            name='avg_humidity',
        ),
        migrations.RemoveField(
            model_name='weatherdaily',
            name='weather_status',
        ),
        migrations.RemoveField(
            model_name='weatherhourly',
            name='feels_like_temp',
        ),
        migrations.RemoveField(
            model_name='weatherhourly',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='weatherhourly',
            name='visibility',
        ),
        migrations.RemoveField(
            model_name='weatherhourly',
            name='weather_status',
        ),
        migrations.AlterField(
            model_name='weatherhourly',
            name='wind_direction',
            field=models.CharField(max_length=10),
        ),
    ]
